### ISSUE TITLE
Mainheading is always constant in the drop down

### ISSUE THREAD

**Issue by georgedevasia0** [Foxiton/bloggenerator#5]
Scenario: I use the "Main heading" only once which is first in the dropdown. I use "paragraph" multiple times and I always need to select paragraph from the dropdown which becomes a hectic task.

Solution: Based on usage, re-arrange the dropdown items list so that it will reduce my difficulty.

**Comment by ashwin347** [comment]
resolved

**Comment by georgedevasia0** [comment]
Working perfectly
